# Generated by Django 2.1.5 on 2019-01-29 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.TextField(default='375440000000', max_length=12, unique=True)),
                ('img', models.ImageField(default='default.jpg', upload_to='user_images')),
                ('activ_user', models.BooleanField(default=False)),
                ('activ_sms', models.BooleanField(default=True)),
                ('done_sum_sms', models.IntegerField(default=0)),
                ('data_input_end_sms', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
