# Generated by Django 2.1.5 on 2019-01-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefon',
            field=models.CharField(default='375447085046', max_length=12, unique=True),
        ),
    ]
