# Generated by Django 2.1.5 on 2019-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_profile_data_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefon',
            field=models.CharField(default='375447085046', max_length=12),
        ),
    ]
