# Generated by Django 2.1.5 on 2019-02-04 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190203_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='data_exit',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
