# Generated by Django 2.1.5 on 2019-02-04 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20190204_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='data_exit',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_exit',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 16, 59, 23, 302210)),
        ),
    ]
