# Generated by Django 2.1.5 on 2019-02-04 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20190204_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_exit',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
