# Generated by Django 2.1.5 on 2019-02-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20190204_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['date_exit']},
        ),
    ]
